version: '3.1'

services:
  db:
    image: postgres:13.8
    container_name: postgres13-container
    env_file:
      - '.env'
    environment:
      POSTGRES_PASSWORD: 2431999
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./data-volume:/var/lib/postgresql/data
    networks:
      - spending_management_prj_network
  api:
    build: .
    image: spending_management_image
    container_name: spending_management_container
    restart: unless-stopped
    env_file:
      - '.env'
    ports:
      - "8080:8000"
    networks:
      - spending_management_prj_network
    depends_on:
      - db

networks:
  spending_management_prj_network:
    driver: bridge